### ISSUE TITLE
DescriptorPool: out of memory

### ISSUE THREAD

**Issue by guilhermegazzinelli** [bigcommerce/gruf#121]
## Please describe the issue
After defining many protos the server is unable to start.

## How to Reproduce

1. defined many protos
2. Try starting server

is there a way to increase memory or any configuration or way to debug this issue?

## What _should_ happen?

Start gruf server

### Sample proto
```proto

syntax = "proto3";

import "AddressModel.proto";
import "ClientCreditModel.proto";
import "ContactModel.proto";
import "Filter.proto";

package remote_proto;

service Clients {
  rpc Index(IndexReq) returns (stream ClientModel) {}
  rpc Show(ShowReq) returns (ShowResp) { }
}

// model
message ClientModel {
  uint32 id = 1;
  string name = 2;
  float price = 3;
  repeated Address addresses = 4;
  repeated Contact contacts = 5;
  ClientCredit client_credit = 6;
}

message IndexReq {
  uint32 limit = 1;
  uint32 page = 2;
  Filter filter = 3;
}

message ShowReq {
  uint64 id = 1;
}

message ShowResp {
  ClientModel client = 1;
}

```
### Generated 
```ruby 
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Clients.proto

require 'google/protobuf'

require 'app/proto/AddressModel_pb'
require 'app/proto/ClientCreditModel_pb'
require 'app/proto/ContactModel_pb'
require 'app/proto/Filter_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proto/Clients.proto", :syntax => :proto3) do
    add_message "remote_proto.ClientModel" do
      optional :id, :uint32, 1
      optional :name, :string, 2
      optional :price, :float, 3
      repeated :addresses, :message, 4, "remote_proto.Address"
      repeated :contacts, :message, 5, "remote_proto.Contact"
      optional :client_credit, :message, 6, "remote_proto.ClientCredit"
    end
    add_message "remote_proto.IndexReq" do
      optional :limit, :uint32, 1
      optional :page, :uint32, 2
      optional :filter, :message, 3, "remote_proto.Filter"
    end
    add_message "remote_proto.ShowReq" do
      optional :id, :uint64, 1
    end
    add_message "remote_proto.ShowResp" do
      optional :client, :message, 1, "remote_proto.ClientModel"
    end
  end
end

module RemoteProto
  ClientModel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("remote_proto.ClientModel").msgclass
  IndexReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("remote_proto.IndexReq").msgclass
  ShowReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("remote_proto.ShowReq").msgclass
  ShowResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("remote_proto.ShowResp").msgclass
end

```
```ruby
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Clients.proto for package 'remote_proto'

require 'grpc'
require 'app/proto/Clients_pb'

module RemoteProto
  module Clients
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'remote_proto.Clients'

      rpc :Index, ::RemoteProto::IndexReq, stream(::RemoteProto::ClientModel)
      rpc :Show, ::RemoteProto::ShowReq, ::RemoteProto::ShowResp
    end

    Stub = Service.rpc_stub_class
  end
end
```
### Error
```bash
bundle exec gruf
bundler: failed to load command: gruf (/home/fusion01/.rbenv/versions/2.6.5/bin/gruf)
Google::Protobuf::TypeError: Unable to add defs to DescriptorPool: out of memory
  /home/fusion01/Documentos/Fusion/Web Cimentao/varejo-api/app/rpc/app/proto/Contacts_pb.rb:9:in `add_file'
  /home/fusion01/Documentos/Fusion/Web Cimentao/varejo-api/app/rpc/app/proto/Contacts_pb.rb:9:in `block in <main>'
  /home/fusion01/Documentos/Fusion/Web Cimentao/varejo-api/app/rpc/app/proto/Contacts_pb.rb:8:in `instance_eval'
  /home/fusion01/Documentos/Fusion/Web Cimentao/varejo-api/app/rpc/app/proto/Contacts_pb.rb:8:in `build'
  /home/fusion01/Documentos/Fusion/Web Cimentao/varejo-api/app/rpc/app/proto/Contacts_pb.rb:8:in `<main>'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
  /home/fusion01/Documentos/Fusion/Web Cimentao/varejo-api/app/rpc/app/proto/Contacts_services_pb.rb:5:in `<main>'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/zeitwerk-2.4.1/lib/zeitwerk/kernel.rb:33:in `require'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'
  /home/fusion01/Documentos/Fusion/Web Cimentao/varejo-api/config/initializers/gruf.rb:4:in `<main>'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:666:in `block in load_config_initializer'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/notifications.rb:182:in `instrument'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:665:in `load_config_initializer'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `each'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/engine.rb:624:in `block in <class:Engine>'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `instance_exec'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:32:in `run'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:61:in `block in run_initializers'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `each'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:50:in `tsort_each_child'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:415:in `call'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/initializable.rb:60:in `run_initializers'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/railties-6.0.3.4/lib/rails/application.rb:363:in `initialize!'
  config/environment.rb:5:in `<top (required)>'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `block in load'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:318:in `load'
  /home/fusion01/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/gruf-2.8.1/bin/gruf:25:in `<top (required)>'
  /home/fusion01/.rbenv/versions/2.6.5/bin/gruf:23:in `load'
  /home/fusion01/.rbenv/versions/2.6.5/bin/gruf:23:in `<top (required)>'
```

* Ruby versions: 2.5.5, 2.6.5 and 2.7.1
* OS: Ubuntu 19.04

**Comment by splittingred** [comment]
Hi @guilhermegazzinelli - this doesn't really seem to be a gruf issue. Gruf doesn't control the amount of memory you allocate to its process; that's typically done via a scheduler (such as k8s) or systemd service - are you getting this error on a laptop, or container, or VM?

It seems to me whatever system you're running this on just isn't allocating enough memory to run a Ruby process.

**Comment by guilhermegazzinelli** [comment]
Its a baremetal machine... I found the problem... Some Services had the same name. So wen we were trying to start server they start to conflict. 
I discovered that just running all the generators from Proto to RB and it shows the name conflict. 

Thanks for all...

**Comment by guilhermegazzinelli** [comment]
Just to Brighten a little more for future reference:
``` ruby
add_message "remote_proto.ShowResp"
```
Distinct modules for proto had these same message name with the same scope. Just a Newbie issue!!!!

The messages must have distinct names or scopes, right @splittingred?
